# Generated by Django 6.0.2 on 2026-09-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.IntegerField(unique=True)),
                ('floor', models.IntegerField(default=1)),
                ('ward', models.CharField(default='Cardiology Ward', max_length=128)),
                ('patient_name', models.CharField(blank=True, max_length=128, null=True)),
                ('patient_mrn', models.CharField(blank=True, max_length=64, null=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('active_alert', models.CharField(blank=True, max_length=64, null=True)),
                ('turnaround_billing_incurred', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventorySKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='CRITICAL_CARE', max_length=64)),
                ('dosage', models.CharField(max_length=128)),
                ('quantity', models.IntegerField(default=20)),
                ('unit', models.CharField(default='vials', max_length=32)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=150.0, max_digits=8)),
                ('min_threshold_percent', models.IntegerField(default=20)),
                ('absolute_floor_units', models.IntegerField(default=15)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IoTLiftBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_id', models.CharField(default='LIFT-MAIN', max_length=64, unique=True)),
                ('active_relay_floor', models.IntegerField(default=2)),
                ('transit_status', models.CharField(default='LEVEL', max_length=64)),
                ('door_status', models.CharField(default='CLOSED', max_length=64)),
                ('is_interlocked', models.BooleanField(default=True)),
                ('pulse_duration_ms', models.IntegerField(default=500)),
                ('last_actuation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.CharField(max_length=64, unique=True)),
                ('requested_by', models.CharField(max_length=128)),
                ('requested_by_role', models.CharField(default='DOCTOR', max_length=32)),
                ('drug_name', models.CharField(max_length=255)),
                ('recommended_dosage', models.CharField(default='Standard Clinical Dose', max_length=128)),
                ('category', models.CharField(default='CRITICAL_CARE', max_length=64)),
                ('target_floor', models.IntegerField(default=2)),
                ('target_bed', models.IntegerField(default=12)),
                ('justification', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING_CHEMIST', 'Pending Chemist Review'), ('APPROVED', 'Approved by Chemist'), ('LOADED', 'Cargo Loaded in Bot'), ('IN_TRANSIT', 'In Autonomous Transit'), ('DELIVERED', 'Delivered to Bedside'), ('REJECTED', 'Rejected')], default='PENDING_CHEMIST', max_length=32)),
                ('passcode_otp', models.CharField(default='4821', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=128, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
